### PR TITLE
Add pledge and cancel pledge tutorial

### PR DESCRIPTION
**Pull request by merc1er**

### CODE REVIEW

**Comment by monsterbitar** [comment]
Based on the deploy preview, this gets my approval.

(I haven't spent time inspecting the actual code though, nor the translations)

**Comment by emergent-reasons** [comment]
I think it looks great. As we just discussed, the only thing that bothers me is the logo being far to the left and translation buttons being far to the right. If they can be bound to the same column width as the content, I think it would be better?

**Comment by merc1er** [comment]
> I think it looks great. As we just discussed, the only thing that bothers me is the logo being far to the left and translation buttons being far to the right. If they can be bound to the same column width as the content, I think it would be better?

Should be fixed in ada2d42

**Comment by emergent-reasons** [comment]
New left/right spacing LGTM.

I'm happy with this as-is. Will ask others to check.

**Review by emergent-reasons — APPROVED** [review]
LGTM. Thanks for fixing a few extra things!

**Pull request merged**
